version: '3.8'

services:
  web:
    build:
      context: ./main
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    
    volumes:
      - ./main/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER={{cookiecutter.project_slug}}
      - POSTGRES_PASSWORD={{cookiecutter.project_slug}}
      - POSTGRES_DB={{cookiecutter.project_slug}}
  {% if cookiecutter.use_celery == 'y' %}    
  celery:
    build: ./main
    command: celery --app=core worker --loglevel=info 
    
    volumes:
      - ./main/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis
 
  redis:
    image: redis:7-alpine
  {% endif %}
volumes:
  postgres_data: